# Generated by Django 4.2.20 on 2025-12-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seb_openedx', '0003_sebcourseconfiguration_allow_mfe_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sebcourseconfiguration',
            name='permission_components',
            field=models.TextField(blank=True, default='AlwaysAllowStaff,CheckSEBHashBrowserExamKeyOrConfigKey'),
        ),
    ]
