# Generated by Django 5.2.13 on 2026-08-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seb_openedx', '0004_alter_sebcourseconfiguration_permission_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sebcourseconfiguration',
            name='allow_mfe_access',
            field=models.BooleanField(default=True),
        ),
    ]
